# Generated by Django 3.2.9 on 2021-12-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appreview', '0003_alter_rating_post'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(fields=('author', 'post'), name='unique_rating'),
        ),
    ]
