# Generated by Django 3.2.9 on 2021-12-15 20:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appreview', '0005_alter_rating_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='screenshot',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='profile_pic'),
        ),
    ]
