# Generated by Django 3.2.9 on 2021-12-15 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appreview', '0006_auto_20211215_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateField(auto_now_add=True),
        ),
    ]
